version: '3'
services:
  node:
    image: node:14
    container_name: nestjs-tasks
    command: bash -c "npm install && npm run start"
    restart: always
    working_dir: '/app'
    volumes:
      - ./:/app
    networks:
      nestkjs_tasks:
        ipv4_address: 10.12.0.2

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=nestjstasks
      - POSTGRES_PASSWORD=a8X0zDLr6B2q
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
    networks:
      nestkjs_tasks:
        ipv4_address: 10.12.0.3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    volumes:
      - ./.volumes/pgadmin_lib:/var/lib/pgadmin
    logging:
      driver: none
    networks:
      nestkjs_tasks:
        ipv4_address: 10.12.0.4

networks:
  nestkjs_tasks:
    ipam:
      driver: default
      config:
        - subnet: '10.12.0.0/24'
